# Generated by Django 5.0.6 on 2024-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="response",
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
